apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-bot-service-account
  namespace: github-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: longhorn-bot-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-bot-binding
  namespace: github-bot
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-bot-role
subjects:
- kind: ServiceAccount
  name: longhorn-bot-service-account
  namespace: github-bot
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: longhorn-runner-binding
  namespace: github-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: longhorn-bot-role
subjects:
- kind: ServiceAccount
  name: longhorn-bot-service-account
  namespace: github-bot
